### ISSUE TITLE
APK available?

### ISSUE THREAD

**Issue by IzzySoft** [Shingyx/BoomSwitch#10]
First thanks for making your app libre & open-source! Would you mind making its APK available outside of Google's walled garden (aka PlayStore) as well, for those outside of it without access? You could e.g. attach it to your [Releases](https://github.com/Shingyx/BoomSwitch/releases). Thanks in advance!

**Comment by Shingyx** [comment]
Hi there, 

I've just uploaded one here - https://github.com/Shingyx/BoomSwitch/releases/tag/v1.4.

Cheers!

**Comment by IzzySoft** [comment]
Thanks a lot! Your app is now [available here](https://apt.izzysoft.de/fdroid/index/apk/com.github.shingyx.boomswitch), too – for folks using the F-Droid client and my repo (which are more than you think). If you wish, you can [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there. My updater runs once a day checking for new tags and fetching APKs attached there, so updates should become available within 24h of your providing them.

In case you wonder about the `NonFreeDep` flag: some of the libs you're using is dragging in GMS. I have a good guess which one: `com.google.android.gms.oss-licenses-plugin`; this is a well known issue of it. If you want to get rid of the "tainting", [take a look here](https://gitlab.com/-/snippets/1896503#license-dialogs) for some hints to alternatives.
