### ISSUE TITLE
v1.4 fails to switch

### ISSUE THREAD

**Issue by Fred-Vatin** [Shingyx/BoomSwitch#12]
Hi,

Since the update, app always returns timeout when trying to switch (ON or OFF).

Reinstalling v1.3 instantly solved the issue.

- Android 11
- UE BOOM 2

**Comment by Shingyx** [comment]
Hi there,

Thanks for reporting the issue. I've reverted what I think was the most suspicious line of code (something added in Android 13) and created a v1.5 release. Can you please give that a try? It should be available shortly.

----

If that still doesn't work, can you please let me know what troubleshooting steps you've tried? Some things to try if you haven't already:

- Update the speaker's firmware using the [official BOOM app](https://play.google.com/store/apps/details?id=com.logitech.ueboom).
- Uninstalling the official BOOM app.
- Restarting your device.

Please let me know how you go. Thanks!

**Comment by Fred-Vatin** [comment]
Perfect. v1.5 solved this issue. Bravo !

**Comment by Shingyx** [comment]
Great! Thank you again for reporting the issue.
