### ISSUE TITLE
signing key changed

### ISSUE THREAD

**Issue by IzzySoft** [Shingyx/BoomSwitch#16]
The APK attached to v1.6 is signed with a key different than the releases before – and there's no information (e.g. with the release notes) what happened. Could you please explain? Changing the signing key means that whoever was already using your app won't be able to update (without uninstalling first, and thus losing all data). They won't even get a notification that a new update is available. Further, a changes key could mean a hostile take-over of your repo, with someone else having attached a manipulated APK.

For details, please see [How to keep your key safe and what measures to take for the event of loss?](https://f-droid.org/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html#lessons-learned-2-how-to-keep-your-key-safe-and-what-measures-to-take-for-the-event-of-loss). Thanks!

**Comment by Shingyx** [comment]
I've updated the apk in the GitHub release. Is the issue resolved now?

**Comment by Shingyx** [comment]
Should be fixed now. I originally sourced the 1.6 apk from the wrong place. Sorry about that, and thanks for reporting the issue.

**Comment by IzzySoft** [comment]
Yes, thanks – that looks good now!

**Comment by IzzySoft** [comment]
Just as a note, something I hadn't thought of "back then": as you let Google do the signing, they also modify the APK (e.g. adding `SOURCE_STAMP_V2_BLOCK` to it and some more). I just tried whether I could establish [Reproducible Builds](https://reproducible-builds.org/) for it (see e.g. [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients) for some background on this), but failed horribly: differences are quite large (DEX diff is more than 200 kB). So if you wanna try for RB, @Shingyx, we'd need the APKs signed by you (and not going via Google).

RB is an optional feature, but recommended: a successful RB confirms your APK was indeed built from the very code it claims to, without anything added or removed. So up to you. We _offer_ you to try, but you're in no way obligated to.
